
package View;

/**
 * Created by cdzos on 2017/5/2.
 *
 * This file is generated by a Python Script
 * DO NOT modify this file manually
 */
public final class StyleFileList {

    public static String[] names = {
        "1337",
        "2112",
        "3024_Day",
        "3024_Night",
        "8-Colour-Dark",
        "Abyss",
        "Acai",
        "Active4D",
        "Anarchist",
        "Angular-io-Code",
        "Array",
        "Codecademy",
        "dimmed-monokai",
        "Facebook",
        "Flatland_Dark",
        "Flatland_Monokai",
    };
}
